title: The Debugging Book
author: Andreas Zeller
copyright: 2021-2025 CISPA Helmholtz Center for Information Security (www.cispa.de). The content of this project is licensed under the Creative Commons Attribution-NonCommercial-ShareAlike 4.0 International License. The source code that is part of the content, as well as the source code used to format and display that content is licensed under the MIT License.
logo: "_static/debuggingbook.png"

bibtex_bibfiles:
  - fuzzingbook.bib

latex:
  latex_documents:
     targetname: debuggingbook.tex

sphinx:
  config:
    latex_engine: xelatex
    latex_show_pagerefs: true
    latex_show_urls: footnote

execute:
  execute_notebooks: 'off'
  stderr_output: show
  timeout: 300

parse:
  myst_enable_extensions:
    # - amsmath
    - colon_fence
    - dollarmath
    # - html_admonition
    # - html_image
    - linkify
    - replacements
    - smartquotes
    - strikethrough
    - substitution
    - tasklist
    - deflist

html:
  announcement: '<p>This is a beta version of debuggingbook.org, currently in development. See the <a href="https://debuggingbook.org/classic/"  style="color:white!important;">classic site</a> for the 2024 version.</p>'
  use_issues_button: true
  use_repository_button: true
  extra_footer: |
    <div>
      Copyright &copy; 2021–2025 <a href="https://www.cispa.de/">CISPA Helmholtz Center for Information Security</a>.
      The <strong>content</strong> of this project is licensed under the <a href="https://creativecommons.org/licenses/by-nc-sa/4.0/">Creative Commons Attribution-NonCommercial-ShareAlike 4.0 International License</a>.
      The <strong>source code</strong> that is part of the content, as well as the source code used to format and display that content is licensed under the <a href="https://github.com/uds-se/debuggingbook/blob/master/LICENSE.md#mit-license">MIT License</a>. <a href="https://cispa.de/en/impressum">Imprint</a>.
      <br>
      <a href="https://cispa.de/en/impressum">Imprint</a> &middot; <a href="/html/index.html#how-do-i-cite-your-work">Cite</a>
    </div>

sphinx:
  config:
    html_show_copyright: false

repository:
  url: "https://github.com/uds-se/debuggingbook/"
  path_to_book: "docs/notebooks"
  branch: master

launch_buttons:
  binderhub_url: "https://mybinder.org"
  thebe: false  # Does not support local imports
